
// This is a mock file. In a real scenario, this would be generated by the RequestFirebaseBackendTool
'use client';
import { createContext, useContext, ReactNode, useMemo } from 'react';
import { FirebaseApp } from 'firebase/app';
import { Auth } from 'firebase/auth';
import { Firestore } from 'firebase/firestore';

interface FirebaseContextType {
    app: FirebaseApp | null;
    auth: Auth | null;
    firestore: Firestore | null;
}

const FirebaseContext = createContext<FirebaseContextType>({ app: null, auth: null, firestore: null });

export const useFirebase = () => useContext(FirebaseContext);
export const useFirebaseApp = () => useContext(FirebaseContext).app;
export const useAuth = () => useContext(FirebaseContext).auth;
export const useFirestore = () => useContext(FirebaseContext).firestore;


export function FirebaseProvider({
    children,
    app,
    auth,
    firestore,
}: {
    children: ReactNode;
    app: FirebaseApp | null;
    auth: Auth | null;
    firestore: Firestore | null;
}) {
    const value = useMemo(() => ({ app, auth, firestore }), [app, auth, firestore]);
    return <FirebaseContext.Provider value={value}>{children}</FirebaseContext.Provider>;
}

export function FirebaseClientProvider({ children }: { children: ReactNode }) {
    // Mock provider, does not initialize firebase
    return <FirebaseProvider app={null} auth={null} firestore={null}>{children}</FirebaseProvider>
}
